"""Central configuration for the Muelltonnen Security application.

Configuration is loaded from a JSON file.
The file may be flat or grouped into nested objects (grouping is only for
readability; see configurations/default_config.json for the default values,
generated by configurations/generate_default_config.py). Relative
`model_path`/`data_dir` values are resolved against the project root.
"""
from __future__ import annotations

import json
import secrets
from dataclasses import dataclass, field, fields
from pathlib import Path
from typing import Any

BASE_DIR = Path(__file__).resolve().parent.parent
CONFIGURATIONS_DIR = BASE_DIR / "configurations"
DEFAULT_CONFIG_PATH = CONFIGURATIONS_DIR / "default_config.json"

_PATH_FIELDS = {"model_path", "data_dir"}


def _resolve_path(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else (BASE_DIR / path)


def _flatten(data: dict[str, Any]) -> dict[str, Any]:
    """Merge a grouped (nested-object) config dict into a single flat mapping."""
    if data and all(isinstance(v, dict) for v in data.values()):
        flat: dict[str, Any] = {}
        for section in data.values():
            flat.update(section)
        return flat
    return dict(data)


@dataclass
class Config:
    # Model / camera
    model_path: str = str(BASE_DIR / "Model" / "Muell+Person_310726_yolo11n_ncnn_model")
    camera_index: int = 0
    frame_width: int = 640
    frame_height: int = 480
    # Target rate at which the main loop reads/processes frames; the loop paces
    # itself (via sleeps) to match this, regardless of the camera's native FPS.
    target_fps: int = 15
    detection_confidence: float = 0.5

    # Class names as defined in Model metadata.yaml
    person_class_name: str = "Person"
    trashbin_class_name: str = "German Trashbin"

    # Ring buffer / recording timing (seconds)
    pre_time: int = 5
    post_time: int = 5

    # Trigger proximity thresholds ("lower and more to the right by at most
    # 60px, or 10% of the frame dimension - whichever is larger")
    trigger_max_pixels: int = 60
    trigger_max_fraction: float = 0.1

    # Storage
    data_dir: Path = field(default_factory=lambda: BASE_DIR / "data")
    captures_dir_name: str = "captures"
    logs_dir_name: str = "logs"
    log_file_name: str = "app.log"
    video_extension: str = ".mp4"
    video_fourcc: str = "mp4v"

    # Web UI
    web_host: str = "0.0.0.0"
    web_port: int = 5000
    web_password: str = "changeme"
    web_secret_key: str = field(default_factory=lambda: secrets.token_hex(32))

    @property
    def captures_dir(self) -> Path:
        return self.data_dir / self.captures_dir_name

    @property
    def logs_dir(self) -> Path:
        return self.data_dir / self.logs_dir_name

    @property
    def log_file(self) -> Path:
        return self.logs_dir / self.log_file_name

    def ensure_directories(self) -> None:
        self.captures_dir.mkdir(parents=True, exist_ok=True)
        self.logs_dir.mkdir(parents=True, exist_ok=True)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Config":
        flat = _flatten(data)
        known_fields = {f.name for f in fields(cls)}
        kwargs: dict[str, Any] = {}
        for name, value in flat.items():
            if name not in known_fields:
                continue
            if name == "model_path":
                value = str(_resolve_path(str(value)))
            elif name == "data_dir":
                value = _resolve_path(str(value))
            kwargs[name] = value
        return cls(**kwargs)

    @classmethod
    def load(cls, path: Path) -> "Config":
        """Load a Config from a JSON file, raising FileNotFoundError/ValueError on failure."""
        if not path.is_file():
            raise FileNotFoundError(f"Configuration file not found: {path}")
        try:
            with path.open("r", encoding="utf-8") as fh:
                data = json.load(fh)
        except json.JSONDecodeError as exc:
            raise ValueError(f"Invalid JSON in configuration file {path}: {exc}") from exc
        if not isinstance(data, dict):
            raise ValueError(f"Configuration file {path} must contain a JSON object.")
        return cls.from_dict(data)
